CREATE DATABASE herb_materia_medica_db;
USE herb_materia_medica_db;


CREATE TABLE herb
(
	id int NOT NULL AUTO_INCREMENT,
	herb_name varchar(255) NOT NULL,
	picked BOOLEAN DEFAULT false,
  	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	PRIMARY KEY(id)
);